version: '3'

networks:
  traefik_net:
    external: true
  onlyoffice:


services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:5.7
    env_file:
      - .env
    networks:
      - onlyoffice
    restart: always
    volumes:
      # - ./config/mysql/conf.d:/etc/mysql/conf.d
      # - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${VOLUMES}/mysql_data:/var/lib/mysql

  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:11.0.0.1458
    depends_on:
      - onlyoffice-mysql-server
    env_file:
      - .env
    networks:
      - onlyoffice
      - traefik_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_net
      - traefik.http.routers.onlyoffice.entrypoints=http
      - traefik.http.routers.onlyoffice.rule=Host("office.${MAKERSPACE_DOMAIN}")
      - traefik.http.middlewares.onlyoffice-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.onlyoffice.middlewares=onlyoffice-https-redirect
      - traefik.http.routers.onlyoffice-secure.entrypoints=https
      - traefik.http.routers.onlyoffice-secure.rule=Host("office.${MAKERSPACE_DOMAIN}")
      - traefik.http.routers.onlyoffice-secure.tls=true
      - traefik.http.routers.onlyoffice-secure.tls.certresolver=http
      - traefik.http.routers.onlyoffice-secure.service=onlyoffice
      - traefik.http.services.onlyoffice.loadbalancer.server.port=80
    restart: always
    privileged: true
    volumes:
      - ${VOLUMES}/community_data:/var/www/onlyoffice/Data
      - ${VOLUMES}/community_log:/var/log/onlyoffice
      - ${VOLUMES}/community_letsencrypt:/etc/letsencrypt

  onlyoffice-control-panel:
    container_name: onlyoffice-control-panel
    depends_on:
      - onlyoffice-community-server
    image: onlyoffice/controlpanel:2.9.0.351
    env_file:
      - .env
    restart: always
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES}/controlpanel_data:/var/www/onlyoffice/Data
      - ${VOLUMES}/controlpanel_log:/var/log/onlyoffice
    networks:
      - onlyoffice
      - traefik_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_net
      - traefik.http.routers.onlyoffice_control.entrypoints=http
      - traefik.http.routers.onlyoffice_control.rule=Host("control.office.${MAKERSPACE_DOMAIN}")
      - traefik.http.middlewares.onlyoffice_control-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.onlyoffice_control.middlewares=onlyoffice_control-https-redirect
      - traefik.http.routers.onlyoffice_control-secure.entrypoints=https
      - traefik.http.routers.onlyoffice_control-secure.rule=Host("control.office.${MAKERSPACE_DOMAIN}")
      - traefik.http.routers.onlyoffice_control-secure.tls=true
      - traefik.http.routers.onlyoffice_control-secure.tls.certresolver=http
      - traefik.http.routers.onlyoffice_control-secure.service=onlyoffice_control
      - traefik.http.services.onlyoffice_control.loadbalancer.server.port=80

