version: '3'

networks:
  backend:
  traefik_net:
    external: true

services:
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    networks:
      - backend
      - traefik_net
#    expose:
#      - '80'
#      - '443'
    volumes:
      - ${VOLUMES}/document_data:/var/www/onlyoffice/Data
      - ${VOLUMES}/document_log:/var/log/onlyoffice

