version: '3'
services:
  openldap:
    image: osixia/openldap
    restart: always
    volumes:
      - /data/ldap/data:/var/lib/ldap
      - /data/ldap/slapd.d:/etc/ldap/slapd.d
    environment:
      LDAP_ORGANISATION: localhost
      LDAP_DOMAIN: localhost
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_TLS_VERIFY_CLIENT: "try"
    ports:
      - "389:389"

  admin:
    image: osixia/phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    networks:
      - default
    ports:
      - 8888:80
