version: '3'

networks:
    backend:
    traefik_net:
        external: true
    prometheus_net:
        external: true
    mail_net:
        external: true

services:

    postgres:
        image: postgres
        volumes:
            - ${VOLUMES}/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password

    keycloak:
        image: quay.io/keycloak/keycloak:22.0.1
        restart: always
        environment:
            - DB_VENDOR=POSTGRES
            - DB_ADDR=postgres
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - DB_USER=${KEYCLOAK_DB_USER}
            - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
            - DB_DATABASE=${KEYCLOAK_DB_NAME}
            - PROXY_ADDRESS_FORWARDING=true
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik_net
            - traefik.http.routers.${SERVICE_NAME}.entrypoints=http
            - traefik.http.routers.${SERVICE_NAME}.rule=Host("login.${MAKERSPACE_DOMAIN}")
            - traefik.http.middlewares.${SERVICE_NAME}-https-redirect.redirectscheme.scheme=https
            - traefik.http.routers.${SERVICE_NAME}.middlewares=${SERVICE_NAME}-https-redirect
            - traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=https
            - traefik.http.routers.${SERVICE_NAME}-secure.rule=Host("login.${MAKERSPACE_DOMAIN}")
            - traefik.http.routers.${SERVICE_NAME}-secure.tls=true
            - traefik.http.routers.${SERVICE_NAME}-secure.tls.certresolver=http
            - traefik.http.routers.${SERVICE_NAME}-secure.service=${SERVICE_NAME}
            - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080
        networks:
            - backend
            - traefik_net
            - prometheus_net
            - mail_net
        depends_on:
            - mssql
            - mssqlscripts
        volumes:
            - ${VOLUMES}/theme:/opt/jboss/keycloak/themes/makerspace
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"

    mail:
        image: elsdoerfer/exim-sender
        restart: always
        volumes:
            - ./tmp/exim:/var/spool/exim4
        environment:
            - PRIMARY_HOST=login.${MAKERSPACE_DOMAIN}
            - ALLOWED_HOSTS=localhost ; keycloak
        expose:
            - 25
        networks:
            - backend
