version: '3'

networks:
    backend:
    traefik_net:
        external: true

services:

    postgres:
        image: postgres
        restart: always
        volumes:
            - ${VOLUMES}/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${KEYCLOAK_DB_NAME}
            POSTGRES_USER: ${KEYCLOAK_DB_USER}
            POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
        networks:
            - backend
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"

    keycloak:
        image: quay.io/keycloak/keycloak:22.0.1
        command: ['start', '--optimized']
        restart: always
        environment:
            JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
            
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://${KEYCLOAK_DB_HOST}/${KEYCLOAK_DB_NAME}
            KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
            KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
            KC_HEALTH_ENABLED: 'true'
            KC_HTTP_ENABLED: 'true'
            KC_METRICS_ENABLED: 'true'
            # KC_HOSTNAME: keycloak.com.au
            # KC_HOSTNAME_PORT: 8180
            KC_HOSTNAME_URL: https://login.${MAKERSPACE_DOMAIN}
            KC_PROXY: reencrypt
            
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: password
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik_net
            - traefik.http.routers.keyloak.entrypoints=http
            - traefik.http.routers.keyloak.rule=Host("login.${MAKERSPACE_DOMAIN}")
            - traefik.http.middlewares.keyloak-https-redirect.redirectscheme.scheme=https
            - traefik.http.routers.keyloak.middlewares=keyloak-https-redirect
            - traefik.http.routers.keyloak-secure.entrypoints=https
            - traefik.http.routers.keyloak-secure.rule=Host("login.${MAKERSPACE_DOMAIN}")
            - traefik.http.routers.keyloak-secure.tls=true
            - traefik.http.routers.keyloak-secure.tls.certresolver=http
            - traefik.http.routers.keyloak-secure.service=keyloak
            - traefik.http.services.keyloak.loadbalancer.server.port=8080
        networks:
            - backend
            - traefik_net
        depends_on:
            - postgres
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"

    mail:
        image: elsdoerfer/exim-sender
        restart: always
        volumes:
            - ./tmp/exim:/var/spool/exim4
        environment:
            - PRIMARY_HOST=login.${MAKERSPACE_DOMAIN}
            - ALLOWED_HOSTS=localhost ; keycloak
        expose:
            - 25
        networks:
            - backend
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
