version: '3.3'

networks:
  net:

services:
  traefik:
    image: traefik:alpine
    restart: always
    command:
      --docker 
      --docker.domain=${MAKERSPACE_URL}
      --docker.watch 
      --web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - net
    logging:
      driver: "json-file"
      options:
          max-file: "1"
          max-size: "100k"