debug = false

# logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.traefik]
  address = ":8080"

[retry]

[api]
entrypoint = "traefik"
dashboard = true



## Try to redirect https to http

# defaultEntryPoints = ["http", "https"]
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.redirect]
#     entryPoint = "http"



## SSL
      
# defaultEntryPoints = ["http", "https"]
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#     [entryPoints.http.redirect]
#     entryPoint = "https"
#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.tls]
#       [[entryPoints.https.tls.certificates]]
#       certFile = "/certs/hn0vweb005.experimenta.science.cer"
#       keyFile = "/certs/hn0vweb005.experimenta.science.key"