version: '3.5'

services:

  redis:
    image: redis
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - backend

  app:
    build: ./app
    restart: always
    labels:
      - traefik.frontend.rule=Host:files.hn0vweb005.experimenta.science
      - traefik.docker.network=traefik_net
      - traefik.port=80
      - traefik.enable=true
    volumes:
      - /data/nextcloud/html:/var/www/html
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: nextcloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 47XPHzdp
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
    env_file:
      - db.env
    depends_on:
      - database
      - redis
    networks:
      - backend
      - traefik_net

  cron:
    build: ./app
    restart: always
    volumes:
      - /data/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - database
      - redis
    labels:
      - traefik.enable=false
    networks:
      - backend

networks:
  backend:
  traefik_net:
    external: true