version: '3.5'

services:

  database:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ${VOLUME_DIR}/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_TABLE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
    labels:
      - traefik.enable=false
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"

  redis:
    image: redis
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"

  app:
    build: ./app
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${NC_HOSTNAME}
      - traefik.docker.network=traefik_net
      - traefik.port=80
    volumes:
      - ${VOLUME_DIR}/html:/var/www/html
      - ${VOLUME_DIR}/data:/data
    environment:
      MYSQL_DATABASE: ${DB_TABLE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: database:3306
      NEXTCLOUD_ADMIN_USER: ${NC_ADMIN}
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD}
      NEXTCLOUD_DATA_DIR: /data
      NEXTCLOUD_TRUSTED_DOMAINS: ${NC_HOSTNAME}
    depends_on:
      - database
      - redis
    networks:
      - backend
      - traefik_net
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"

  cron:
    build: ./app
    restart: always
    volumes:
      - ${VOLUME_DIR}/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - database
      - redis
    labels:
      - traefik.enable=false
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"

networks:
  backend:
  traefik_net:
    external: true
