version: '3.5'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/cloud-hmnd-de/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  redis:
    image: redis
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - backend

  app:
    build: ./app
    restart: always
    labels:
      - traefik.frontend.rule=Host:${NC_HOSTNAME}
      - traefik.docker.network=traefik_net
      - traefik.port=80
      - traefik.enable=true
    volumes:
      - /data/cloud-hmnd-de/html:/var/www/html
      - /data/cloud-hmnd-de/data:/data
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NC_ADMIN}
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD}
      NEXTCLOUD_DATA_DIR: /data
      NEXTCLOUD_TRUSTED_DOMAINS: ${NC_HOSTNAME}
    depends_on:
      - database
      - redis
    networks:
      - backend
      - traefik_net

  cron:
    build: ./app
    restart: always
    volumes:
      - /data/cloud-hmnd-de/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - database
      - redis
    labels:
      - traefik.enable=false
    networks:
      - backend

networks:
  backend:
  traefik_net:
    external: true
