# NOTE: This files purpose is to spin-up the project for testing it in CI. 
#       Please do not understand it as recommendation for an production 
#       docker-compose setup. For that see the README. If you have additions 
#       to make, please add them there.
version: '3.1'

networks:
  traefik_net:
    external: true
  backend:

services:
  humhub:
    build: .
    networks:
      - traefik_net
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_net
      - traefik.http.routers.humhub.entrypoints=http
      - traefik.http.routers.humhub.rule=Host("community.${MAKERSPACE_HOSTNAME}")
      - traefik.http.middlewares.humhub-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.humhub.middlewares=humhub-https-redirect
      - traefik.http.routers.humhub-secure.entrypoints=https
      - traefik.http.routers.humhub-secure.rule=Host("community.${MAKERSPACE_HOSTNAME}")
      - traefik.http.routers.humhub-secure.tls=true
      - traefik.http.routers.humhub-secure.tls.certresolver=http
      - traefik.http.routers.humhub-secure.service=humhub
      - traefik.http.services.humhub.loadbalancer.server.port=80
    environment:
      HUMHUB_DB_USER: ${HUMHUB_DB_USER}
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
      HUMHUB_DB_HOST: 'db'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 0
      HUMHUB_DEBUG: 0
      HUMHUB_PROTO: 'https'
      HUMHUB_HOST: 'community.${MAKERSPACE_HOSTNAME}'
      HUMHUB_ADMIN_LOGIN: ${HUMHUB_ADMIN_LOGIN}
      HUMHUB_ADMIN_EMAIL: ${HUMHUB_ADMIN_EMAIL}
      HUMHUB_ADMIN_PASSWORD: ${HUMHUB_ADMIN_PASSWORD}
      # Mailer install setup
      HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS: 'makerspace@experimenta.science'
      HUMHUB_MAILER_SYSTEM_EMAIL_NAME: 'Maker Space'
      HUMHUB_MAILER_TRANSPORT_TYPE: 'smtp'
      HUMHUB_MAILER_HOSTNAME: 'mailer'
      HUMHUB_MAILER_PORT: 1025
      #HUMHUB_MAILER_USERNAME:
      #HUMHUB_MAILER_PASSWORD:
      #HUMHUB_MAILER_ENCRYPTION:
      HUMHUB_MAILER_ALLOW_SELF_SIGNED_CERTS: 0
      # Cache Config
      HUMHUB_CACHE_EXPIRE_TIME: 3600
      HUMHUB_CACHE_CLASS: yii\redis\Cache
      HUMHUB_QUEUE_CLASS: humhub\modules\queue\driver\Redis
      HUMHUB_REDIS_HOSTNAME: redis
      HUMHUB_REDIS_PORT: 6379
      HUMHUB_REDIS_PASSWORD: redis_password
#   volumes:
#     - "${HUMHUB_VOLUME_CONFIG}:/var/www/localhost/htdocs/protected/config"
    volumes:
      - ${VOLUME_DIR}/config:/var/www/localhost/htdocs/protected/config
      - ${VOLUME_DIR}/uploads:/var/www/localhost/htdocs/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb
    networks:
      - backend
    volumes:
      - ${VOLUME_DIR}/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3

  mailer:
    image: sj26/mailcatcher:latest
    restart: always
    networks:
      - backend
    expose:
      - 1025
#    ports:
#      - "1080:1080"

  redis:
    image: redis:5.0-alpine
    networks:
      - backend
#    expose:
#      - '6379'
#    volumes:
#      - /srv/humhub/redis:/data
    environment:
      - REDIS_PASSWORD=redis_password
      #- ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

