version: "3"

services:
  frontend:
    image: nginx
    restart: always
    volumes:
      - ./app:/usr/share/nginx/html
    labels:
      - traefik.frontend.rule=Host:makerspace.experimenta.science
      - traefik.docker.network=traefik_net
      - traefik.enable=true
      - traefik.port=80
    networks:
      - traefik_net
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"

networks:
  traefik_net:
    external: true

