version: '3.3'

networks:
    backend:
    traefik_net:
        external: true

services:
    
    db:
        image: mysql:5.7
        volumes:
            - ${WORDPRESS_DIR}/db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks: 
            - backend
        labels:
            - "traefik.enable=false"
    


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8080:80
        depends_on: 
            - db
        environment:
            PMA_HOST: ${MYSQL_HOST}
        networks:
            - backend
        labels:
            - "traefik.enable=false"

    wordpress:
        image: wordpress:latest
        restart: always
        environment:
            WORDPRESS_DB_HOST: ${MYSQL_HOST}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${WORDPRESS_DIR}/wordpress:/var/www/html
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            #- ./wp-config.php:/var/www/html/wp-config.php
        networks:
            - backend
            - traefik_net
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.frontend.rule=Host:${MAKERSPACE_URL}
            - traefik.docker.network=traefik_net