version: '3.3'

networks:
  backend:
  traefik_net:
    external: true

services:
  wordpress:
    build: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MAKERSPACE_DB_HOST}
      WORDPRESS_DB_NAME: ${MAKERSPACE_DB_NAME}
      WORDPRESS_DB_USER: ${MAKERSPACE_DB_USER}
      WORDPRESS_DB_PASSWORD: ${MAKERSPACE_DB_PASSWORD}
    volumes:
      - /data/wordpress/data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - backend
      - traefik_net
    labels:
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:${MAKERSPACE_URL}"
    - "traefik.docker.network=traefik_net"