version: '3.3'

networks:
    backend:
    traefik_net:
        external: true

services:
    
    db:
        image: mysql:5.7
        volumes:
            - ${WORDPRESS_DIR}/db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks: 
            - backend
        labels:
            - "traefik.enable=false"
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
    


    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     restart: unless-stopped
    #     ports:
    #         - 8081:80
    #     depends_on: 
    #         - db
    #     environment:
    #         PMA_HOST: ${MYSQL_HOST}
    #     networks:
    #         - backend
    #     labels:
    #         - "traefik.enable=false"
    #     volumes: 
    #         - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    #     logging:
    #         driver: "json-file"
    #         options:
    #             max-file: "1"
    #             max-size: "100k"

    wordpress:
        build: ./app
        restart: always
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: ${MYSQL_HOST}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${WORDPRESS_DIR}/wordpress:/var/www/html
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            # - ${MAKERSPACE_PATH_THEMES}:/var/www/html/wp-content/themes
            # - ${MAKERSPACE_PATH_PLUGINS}:/var/www/html/wp-content/plugins
            # - ./wp-config.php:/var/www/html/wp-config.php
        networks:
            - backend
            - traefik_net
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik_net
            - traefik.http.routers.wordpress.entrypoints=http
            - traefik.http.routers.wordpress.rule=Host("${MAKERSPACE_URL")
            - traefik.http.middlewares.wordpress-https-redirect.redirectscheme.scheme=https
            - traefik.http.routers.wordpress.middlewares=wordpress-https-redirect
            - traefik.http.routers.wordpress-secure.entrypoints=https
            - traefik.http.routers.wordpress-secure.rule=Host("${MAKERSPACE_URL")
            - traefik.http.routers.wordpress-secure.tls=true
            - traefik.http.routers.wordpress-secure.tls.certresolver=http
            - traefik.http.routers.wordpress-secure.service=wordpress
            - traefik.http.services.wordpress.loadbalancer.server.port=80
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
