version: '3'

networks:
  traefik_net:
    external: true
  backend:
    external: true

services:
  openldap:
    image: osixia/openldap
    restart: always
    volumes:
      - ${VOLUME_DIR}/data:/var/lib/ldap
      - ${VOLUME_DIR}/slapd.d:/etc/ldap/slapd.d
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"
    environment:
      LDAP_ORGANISATION: ${MAKERSPACE_LDAP_ORGANIZATION}
      LDAP_DOMAIN: ${MAKERSPACE_LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${MAKERSPACE_LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${MAKERSPACE_LDAP_CONFIG_PASSWORD}
      LDAP_TLS_VERIFY_CLIENT: "try"
    ports:
      - "389:389"
    labels:
      - traefik.enable=false
    networks:
      - backend

  admin:
    image: osixia/phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    networks:
    - backend
    - traefik_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_net
      - traefik.http.routers.ldap.entrypoints=http
      - traefik.http.routers.ldap.rule=Host("${MAKERSPACE_LDAP_URL}")
      - traefik.http.services.ldap.loadbalancer.server.port=80
