version: '3.5'

services:

  database:
    image: mysql:5.7
    volumes:
      - "dbdata:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    depends_on: 
      - database
    environment:
      PMA_HOST: database
    networks:
      - backend

  openldap:
    image: osixia/openldap
    restart: always
    volumes:
      - /data/ldap/data:/var/lib/ldap
      - /data/ldap/slapd.d:/etc/ldap/slapd.d
    environment:
      LDAP_ORGANISATION: localhost
      LDAP_DOMAIN: localhost
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_TLS_VERIFY_CLIENT: "try"
    ports:
      - "389:389"
    networks:
      - backend

  admin:
    image: osixia/phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    networks:
      - backend
    ports:
      - 8888:80

networks:
  backend:

volumes:
  dbdata:
